#!/usr/bin/env python3
import argparse
import sys
import re

def parseArguments():
    parser = argparse.ArgumentParser(description='multisub - Perform regex replacement operations based on grep-output-like input files')
    parser.add_argument('input', help="File/input stream containing list of lines with pattern: <filepath><separator><lineno>[optional rest of line], typically obtained via grep (or structviz tool).", type=argparse.FileType("r"), nargs="?", default=sys.stdin)
    parser.add_argument('-p,--patterns', dest="patterns", required=False, type=str, nargs="+", help=r"Search patterns (first, third, ...) and their replacement (second, fourth, ...). List must have even length.",default=[])
    parser.add_argument('-d,--delete-patterns', dest="deletePatterns", required=False, type=str, nargs="+", help=r"Patterns to delete",default=[])
    parser.add_argument('-e,--erase-lines', dest="eraseLinePatterns", required=False, type=str, nargs="+", help=r"Erase whole lines that contain one of the specified patterns.",default=[])
    parser.add_argument('-w,--wrap-in-ifelse', dest="wrapInIf", default="", nargs="?", help="Wrap modified and original line in '#if<expression> <modified> #else <original> #endif' construct ")
    parser.add_argument('--separator', type=str, default=r":-", nargs="?", help=r"Characters regarded as separator between filepath and lineno [default=':-']")
    parser.add_argument('-s,--case-sensitive', dest="ignoreCase", action="store_false", help="Do not ignore case when search for patterns [default=False]")
    parser.add_argument('-l,--lower', dest="lower", action="store_true", help="Convert ALL replacements to lower case")
    parser.add_argument('-u,--upper', dest="upper", action="store_true", help="Convert ALL replacements to upper case")
    parser.add_argument('-i,--in-place', dest="inplace", action="store_true", help="Apply replacement action directly to original file(s) [default=False]")
    parser.add_argument('-a,--write-input-lines', dest="writeInputLines", required=False, action="store_true", help="Write lines as specified in the input file to the destination file(s). Has precedence over other modifications.",default=[])
    parser.add_argument('-v,--verbose', dest="verbose", action="store_true", help="Verbose output")
    parser.add_argument('-c,--show-only-changes', dest="noOutput", action="store_true", help="Show only changes do not generate any output (to stdout or orginal file)")
    parser.set_defaults(ignoreCase=True,verbose=False,inplace=False,noOutput=False,writeInputLines=False)
    return parser.parse_args()

args = parseArguments()
if args.lower and args.upper:
    print("ERROR: please specify only one of upper ('-u') and lower ('-l'). ABORT".format(filepath,lineno),file=sys.stderr)
# parsing
flag = re.IGNORECASE if args.ignoreCase else 0
locatorPattern = re.compile(r"(?P<filepath>.+)[\s{0}]+(?P<lineno>[0-9]+)[{0}](?P<text>.+$)".format(args.separator), flag)
if not args.writeInputLines and not len(args.patterns) and not len(args.deletePatterns) and not len(args.eraseLinePatterns):
   print("ERROR: please specify either replace patterns ('-p'), delete patterns ('-d'), erase line patterns ('-e') or the '-a' switch. ABORT".format(filepath,lineno),file=sys.stderr)
   sys.exit(2)
if len(args.patterns) % 2 > 0:
   print("ERROR: list of search and replace patterns is not even. ABORT".format(filepath,lineno),file=sys.stderr)
   sys.exit(2)
for pattern in args.deletePatterns:
   args.patterns.append(pattern)
   args.patterns.append("")

# convert input into convenient format
# we want to open files only once.
locations = {}

for line in args.input.readlines():
    m = locatorPattern.match(line)
    if m:
       filepath = m.group("filepath")
       lineno   = int(m.group("lineno"))
       text     = m.group("text")
       if args.verbose:
          print("INFO: found filepath '{0}' and line number '{1}'.".format(filepath,lineno),file=sys.stderr)
       if not filepath in locations:
           locations[filepath] = []
       locations[filepath].append( (lineno,text.rstrip("\n")) )
    else:
       print("WARNING: input line '{0}' is not in format '<filepath><separator><lineno>[optional rest of line]'. Is ignored.".format(line),file=sys.stderr)

# no go through the lines and replace all search patterns by the replacement pattern in the specified lines
for filepath,entries in locations.items():
    outputlines = []
    with open(filepath,"r") as target:
        for lineno, line in enumerate(target.readlines()):
            modLine = line.rstrip("\n")
            entry = next((entry for entry in entries if lineno+1 == entry[0]),None)
            if entry:
                # apply
                if args.writeInputLines:
                    if (args.verbose or args.noOutput) and entry[1] != modLine:
                       print("INFO: {0}:{1}: replace '{3}' -> '{2}'".format(filepath,lineno+1,entry[1],modLine),file=sys.stderr)
                    modLine = entry[1]
                # erase lines
                eraseLine = False
                for pattern in args.eraseLinePatterns:
                    pEraseLine = re.compile(r"{0}".format(pattern))
                    if pEraseLine.search(line):
                        if (args.verbose or args.noOutput):
                            print("INFO: {0}:{1}: erase line '{2}'".format(filepath,lineno+1,modLine),file=sys.stderr)
                        eraseLine = True
                        break
                # change line content if line must not be deleted
                if not eraseLine:
                    for i in range(0,int(len(args.patterns)/2)):
                        prevModLine = modLine
                        if args.lower or args.upper:
                            def replaceAndChangeCase(m):
                                """
                                Callback is only applied to matching string
                                """
                                result = re.sub(pattern = r"{0}".format(args.patterns[2*i]),\
                                                repl    = r"{0}".format(args.patterns[2*i+1]),\
                                                string  = m.group(0),\
                                                count   = 0, flags = flag) # 0 - replace all matches
                                if args.lower:
                                    return result.lower()
                                elif args.upper:
                                    return result.upper()
                            modLine = re.sub(pattern = r"{0}".format(args.patterns[2*i]),\
                                             repl    = replaceAndChangeCase,\
                                             string  = modLine,\
                                             count   = 0, flags = flag) # 0 - replace all matches
                        else:
                            modLine = re.sub(pattern = r"{0}".format(args.patterns[2*i]),\
                                             repl    = r"{0}".format(args.patterns[2*i+1]),\
                                             string  = modLine,\
                                             count   = 0, flags = flag) # 0 - replace all matches
                        if (args.verbose or args.noOutput) and prevModLine != modLine:
                            print("INFO: {0}:{1}: replace '{2}' -> '{3}'".format(filepath,lineno+1,prevModLine,modLine),file=sys.stderr)

                    newlines = []
                    if len(args.wrapInIf):
                        newlines.append("#if{}\n".format(args.wrapInIf))
                    if modLine != "":
                        newlines += ["{0}\n".format(el) for el in modLine.split("\n")]
                    if len(args.wrapInIf):
                        newlines.append("#else\n")
                        newlines.append(line)
                        newlines.append("#endif\n")
                        if args.verbose or args.noOutput:
                             print("INFO: {0}:{1}: replace '{2}' -> '{3}'".format(filepath,lineno,prevModLine,"".join(newlines)),file=sys.stderr)
                    outputlines += newlines 
            else:
                outputlines.append(line)
    if len(outputlines):
        outputlines[-1] = outputlines[-1].rstrip("\n")
    if not args.noOutput:
        if args.inplace:
            if args.verbose:
                print("INFO: directly apply changes to original file '{0}'".format(filepath),file=sys.stderr)
            with open(filepath,"w") as target:
                target.writelines(outputlines)
        else: 
            print("".join(outputlines))
